version: 2.1

defaults: &defaults
  resource_class: small
  docker:
    - image: cimg/node:10.24.1
  working_directory: ~/policy

commands:
  install_deps:
    description: Install dependencies
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-cache-{{ checksum "package-lock.json" }}
            - v1-npm-cache-
      - run:
          name: Create .npmrc
          command: echo "//registry.npmjs.org/:_authToken=${NPMJS_TOKEN}" >> .npmrc
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - persist_to_workspace:
          root: .
          paths:
            - node_modules/

jobs:
  install:
    <<: *defaults
    steps:
      - install_deps
  lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/policy
      - run:
          name: Run linting
          command: npm run lint
  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/policy
      - run:
          name: Run tests
          command: npm run test -- --ci
      - store_test_results:
          path: reports/jest/
      - store_artifacts:
          path: reports/jest/
  release:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Release on GitHub
          command: npx semantic-release

workflows:
  version: 2
  test_and_release:
    jobs:
      - install:
          name: Install
          context: nodejs-lib-release
          filters:
            branches:
              ignore:
                - master
      - lint:
          name: Lint
          context: nodejs-lib-release
          requires:
            - Install
          filters:
            branches:
              ignore:
                - master
      - test:
          name: Test
          context: nodejs-lib-release
          requires:
            - Lint
          filters:
            branches:
              ignore:
                - master
      - release:
          name: Release
          context: nodejs-lib-release
          filters:
            branches:
              only:
                - master
