version: 2.1

defaults: &defaults
  resource_class: small
  working_directory: ~/policy

executors:
  docker-node-10:
    docker:
      - image: cimg/node:10.24.1
  docker-node:
    parameters:
      version:
        default: '10.24.1'
        type: string
    docker:
      - image: cimg/node:<<parameters.version>>

commands:
  install_deps:
    description: Install dependencies
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-cache-{{ checksum "package-lock.json" }}
            - v1-npm-cache-
      - run:
          name: Create .npmrc
          command: echo "//registry.npmjs.org/:_authToken=${NPMJS_TOKEN}" >> .npmrc
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - persist_to_workspace:
          root: .
          paths:
            - node_modules/

jobs:
  install:
    <<: *defaults
    executor:
      name: docker-node-10
    steps:
      - install_deps
  lint:
    <<: *defaults
    executor:
      name: docker-node-10
    steps:
      - checkout
      - attach_workspace:
          at: ~/policy
      - run:
          name: Run linting
          command: npm run lint
  test:
    <<: *defaults
    parameters:
      version:
        default: '10.24.1'
        type: string
    executor:
      name: docker-node
      version: <<parameters.version>>
    steps:
      - checkout
      - attach_workspace:
          at: ~/policy
      - run:
          name: Run tests
          command: npm run test -- --ci
      - store_test_results:
          path: reports/jest/
      - store_artifacts:
          path: reports/jest/
  release:
    <<: *defaults
    executor:
      name: docker-node-10
    steps:
      - checkout
      - install_deps
      - run:
          name: Release on GitHub
          command: npx semantic-release

workflows:
  version: 2
  test_and_release:
    jobs:
      - install:
          name: Install
          context: nodejs-lib-release
          filters:
            branches:
              ignore:
                - master
      - lint:
          name: Lint
          context: nodejs-lib-release
          requires:
            - Install
          filters:
            branches:
              ignore:
                - master
      - test:
          name: Test
          context: nodejs-lib-release
          requires:
            - Lint
          matrix:
            parameters:
              version:
                - 8.17.0
                - 10.24.1
                - 12.22.1
          filters:
            branches:
              ignore:
                - master
      - release:
          name: Release
          context: nodejs-lib-release
          filters:
            branches:
              only:
                - master
